package http

import (
	"github.com/ritterhou/stinger/core/common"
	"log"
	"strconv"
	"strings"
)

const origin = `// Generated by stinger.
const proxyHost = 'SOCKS5 PROXY_HOST';
const domains = [
PROXY_DOMAINS];

function FindProxyForURL(url, host) {
    for (let i = 0; i < domains.length; i++) {
        if (url.indexOf(domains[i]) !== -1) {
            return proxyHost;
        }
    }
    return 'DIRECT';
}
`

var pacFile string

func CreatePacFile(localPort int, global bool, domains []interface{}) {
	proxyHost := common.GetIp() + ":" + strconv.Itoa(localPort)
	if global {
		pacFile = `// Generated by stinger.
function FindProxyForURL(url, host) {
    return 'SOCKS5 ` + proxyHost + `';
}
`
	} else {
		pacFile = strings.Replace(origin, "PROXY_HOST", proxyHost, 1)
		proxyDomains := ""
		for _, domain := range domains {
			proxyDomains += "    '" + domain.(string) + "',\n"
		}
		pacFile = strings.Replace(pacFile, "PROXY_DOMAINS", proxyDomains, 1)
	}
	log.Println("Create pac file success, pac file: \n" + pacFile)
}

// 获取PAC文件
func getPac() string {
	return pacFile
}
