package http

import (
	"github.com/ritterhou/stinger/core/common"
	"log"
	"strconv"
	"strings"
)

const origin = `// Generated by stinger.
const proxyHost = 'SOCKS5 PROXY_HOST';
const domains = [
PROXY_DOMAINS];

function FindProxyForURL(url, host) {
    for (let i = 0; i < domains.length; i++) {
        if (url.indexOf(domains[i]) !== -1) {
            return proxyHost;
        }
    }
    return 'DIRECT';
}
`

var pacFile string

func CreatePacFile(localPort int, domains []interface{}) {
	proxyDomains := ""
	for _, domain := range domains {
		proxyDomains += "    '" + domain.(string) + "',\n"
	}
	pacFile = strings.Replace(origin, "PROXY_DOMAINS", proxyDomains, 1)

	proxyHost := common.GetIp() + ":" + strconv.Itoa(localPort)
	pacFile = strings.Replace(pacFile, "PROXY_HOST", proxyHost, 1)
	log.Println("Create pac file success, pac file: \n" + pacFile)
}

// 获取PAC文件
func getPac() string {
	return pacFile
}
